spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_NAME}
    password: ${DB_PASSWORD}
  jpa:

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  logging:
    level:
      org:
        hibernate:
          SQL: debug
          type: trace

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USER}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    jwt:
      header : Authorization
      secret : ${JWT_TOKEN}
      token-validity-in-seconds : 86400


