spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver  # MariaDB ???? ??
    url: jdbc:mariadb://localhost:3306/2human  # MySQL ?????? URL
    username: root # MySQL ??? ??
    password:  # MySQL ????

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL Dialect? ??
    hibernate:
      ddl-auto: update
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
